### PR TITLE
Base32-encode only invalid runc format substrings

### LINKED ISSUE #109: cgroup-path
**TLDR:**
1. prepend `bpm` to the cgroup path
2. do not base32 encode the container id

**Details:**

In a [previous story](https://www.pivotaltracker.com/n/projects/2070399/stories/150819404), the decision was to base32 encode the job name for the runc container-id which becomes the cgroup-path in the file `/proc/[pid]/cgroup`:
```
hierarchy-ID:controller-list:cgroup-path
``` 

I would like to write a [sysdig-bosh release](https://github.com/ansd/sysdig-boshrelease) which will be colocated on VMs and which should ideally also be able to monitor bpm containers. Sysdig parses the cgroup-path in order to classify the container type (see [here](https://github.com/draios/sysdig/blob/f27e1ca1f17cbe6a463b7e248867c488f49fecf4/userspace/libsinsp/container.cpp#L581) for LXC).
For example, the cgroup-path for an LXC container looks like `/lxc/my-container`:
```
cat /proc/<pid of lxc container>/cgroup
11:hugetlb:/lxc/my-container
```

It's the default for LXC (see [here](https://linuxcontainers.org/lxc/manpages/man5/lxc.system.conf.5.html)):
```
lxc.cgroup.pattern
Format string used to generate the cgroup path (e.g. lxc/%n).
```

According to the sysdig code, the same applies to [mesos](https://github.com/draios/sysdig/blob/f27e1ca1f17cbe6a463b7e248867c488f49fecf4/userspace/libsinsp/container.cpp#L684), [libvirt-lxc](https://github.com/draios/sysdig/blob/f27e1ca1f17cbe6a463b7e248867c488f49fecf4/userspace/libsinsp/container.cpp#L616) and [docker](https://github.com/draios/sysdig/blob/f27e1ca1f17cbe6a463b7e248867c488f49fecf4/userspace/libsinsp/container.cpp#L480).
Only the bpm container has this base32 encoded cgroup-path like
```
12:pids:/MJWG6YTTORXXEZI-
```
for the blobstore for example.

Having prepended something like `bpm.` to the cgroup-path would allow to parse it easily in sysdig such that the filter `csysdig -pc container.type=bpm` could match BPM containers.

But even though if the cgroup-path looks like `bpm.MJWG6YTTORXXEZI-`, the output for above filter would show a container column with the name `MJWG6YTTORXXEZI-` rather than `blobstore`.

Therefore, it would also be better to not base32 encode the whole container name, but encode maybe only those chars which do not match the regex `^[\w+-\.]+$` (see [code](https://github.com/opencontainers/runc/blob/079817cc26ec5292ac375bb9f47f373d33574949/libcontainer/factory_linux.go#L32)). This would probably require to have a special delimiter char for the decoding process in order to identify the encoded chars.

See also [Slack discussion](https://cloudfoundry.slack.com/archives/C7A0K6NMU/p1541758095018100) for more context.

If the above two requirements are okay with you, I could also create a PR.

### PR DESCRIPTION
**Pull request by ansd**
Also, prepend "bpm-" to the container ID.

Close #109

### CODE REVIEW

**Comment by xoebus** [comment]
Thanks for the PR! I should have time to review it next week.

**Comment by xoebus** [comment]
Hey there, thanks for working on this and sending this PR. We had a look over it at the end of last week.

We were unanimously in favor of adding some sort of `bpm-` prefix to the container IDs. However, we were concerned about the number of escaping characters added in the common case of one special character e.g. https://github.com/cloudfoundry-incubator/bpm-release/pull/111/files#diff-f63501a92bf2fba6a6a55e3e52b08d15R29.

I've been experimenting with some different encoding formats to get around this in the `jobid` branch: https://github.com/cloudfoundry-incubator/bpm-release/commit/5a3953049eb42ac2d01154dabb4583f41a19a996.

**Comment by ansd** [comment]
@xoebus, thanks for your feedback.
I also prefer your hex encoding of individual invalid chars.
How should we proceed? Do we close this PR and you merge your branch once it's ready?

**Comment by xoebus** [comment]
Sure! We can link it all through your original issue: https://github.com/cloudfoundry-incubator/bpm-release/issues/109.

**Pull request closed without merging**
