### PR TITLE
Update NOTICE

### PR DESCRIPTION
**Pull request by christopherclark**
Corrected copyright

### CODE REVIEW

**Comment by xoebus** [comment]
Thanks! This is a legacy from before this was a CF Foundation project. The notice is still in all of the source files too. I'll update the test and the rest of the files.

**Comment by xoebus** [comment]
@christopherclark I've made the rest of the changes in #34. Does that PR look good to you?

**Comment by christopherclark** [comment]
Perfect.  Thank you!

**Comment by christopherclark** [comment]
@xoebus

**Pull request closed without merging**
